name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:   
    - name: AWS IAM Assume Role
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

          #role-session-name: GH-Actions-${{ env.project }}
    - name: Deploy static site to S3 bucket
      run: aws s3 sync kamya/public/ s3://elasticbeanstalk-ap-south-1-031409194969
  
