name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credential
      uses: aws-actions/configure-aws-credentials@v1
      with:
            aws-access-key-id: AKIAQOUBCI7MVIMWAA5K
            aws-secret-access-key: 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
            aws-region: ap-southeast-1
            role-to-assume: s3role
            role-external-id: arn:aws:iam::031409194969:role/s3role
            role-duration-seconds: 1200
          #  role-session-name: MySessionName
    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./public/ s3://elasticbeanstalk-ap-south-1-031409194969
  
